set_property PACKAGE_PIN U18 [get_ports resonator_clk]
set_property IOSTANDARD LVCMOS33 [get_ports resonator_clk]

# keys
set_property PACKAGE_PIN H18 [get_ports J11_K0]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K0]
set_property PACKAGE_PIN J18 [get_ports J11_K1]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K1]
set_property PACKAGE_PIN G20 [get_ports J11_K2]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K2]
set_property PACKAGE_PIN G19 [get_ports J11_K3]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K3]
set_property PACKAGE_PIN F16 [get_ports J11_K4]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K4]
set_property PACKAGE_PIN F17 [get_ports J11_K5]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K5]
set_property PACKAGE_PIN F19 [get_ports J11_K6]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K6]
set_property PACKAGE_PIN F20 [get_ports J11_K7]
set_property IOSTANDARD LVCMOS33 [get_ports J11_K7]

# LED SEL
set_property PACKAGE_PIN W19 [get_ports SMG_0]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_0]
set_property PACKAGE_PIN R14 [get_ports SMG_1]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_1]
set_property PACKAGE_PIN Y17 [get_ports SMG_2]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_2]
set_property PACKAGE_PIN W15 [get_ports SMG_3]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_3]
set_property PACKAGE_PIN Y14 [get_ports SMG_4]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_4]
set_property PACKAGE_PIN P18 [get_ports SMG_5]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_5]
set_property PACKAGE_PIN U15 [get_ports SMG_6]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_6]
set_property PACKAGE_PIN P16 [get_ports SMG_7]
set_property IOSTANDARD LVCMOS33 [get_ports SMG_7]
# LED CON
set_property PACKAGE_PIN W18 [get_ports CON_A]
set_property IOSTANDARD LVCMOS33 [get_ports CON_A]
set_property PACKAGE_PIN P14 [get_ports CON_B]
set_property IOSTANDARD LVCMOS33 [get_ports CON_B]
set_property PACKAGE_PIN Y16 [get_ports CON_C]
set_property IOSTANDARD LVCMOS33 [get_ports CON_C]
set_property PACKAGE_PIN V15 [get_ports CON_D]
set_property IOSTANDARD LVCMOS33 [get_ports CON_D]
set_property PACKAGE_PIN W14 [get_ports CON_E]
set_property IOSTANDARD LVCMOS33 [get_ports CON_E]
set_property PACKAGE_PIN N17 [get_ports CON_F]
set_property IOSTANDARD LVCMOS33 [get_ports CON_F]
set_property PACKAGE_PIN U14 [get_ports CON_G]
set_property IOSTANDARD LVCMOS33 [get_ports CON_G]
set_property PACKAGE_PIN P15 [get_ports CON_DP]
set_property IOSTANDARD LVCMOS33 [get_ports CON_DP]